export type ValorantMapData = {
  slug: string
  titleJa: string
  titleEn: string
  subtitle: string
  overview: string
  attackLabel: string
  defendLabel: string
  focusLabel: string
  attackPoints: string[]
  defendPoints: string[]
  focusPoints: string[]
  mapPickRate: number
  memo: string
  trackerSlug: string
  currentRotation: boolean
  appMediaUrl: string
  detailImage: string
  cardImage: string
}

export const VALORANT_MAPS: ValorantMapData[] = [
  {
    slug: 'haven',
    titleJa: 'ヘイヴン',
    titleEn: 'Haven',
    subtitle: 'VALORANT MAP DETAIL',
    overview: '3サイト構成で守りの配置が難しく、攻めは人数差を作って一気に崩す動きが重要です。',
    attackLabel: '攻め',
    defendLabel: '守り',
    focusLabel: '意識したい点',
    attackPoints: ['3サイトのどこを攻めるかを早めに決める', 'ミッド圧で守りの人数配分を崩す'],
    defendPoints: ['AとCの寄り速度を意識する', '情報スキルで空いているサイトを減らす'],
    focusPoints: ['ミッド周りの主導権', '寄りとローテーション速度'],
    mapPickRate: 49,
    memo: 'サイト数が多く、情報取得と寄り判断の質がそのまま勝率に繋がります。',
    trackerSlug: 'haven',
    currentRotation: true,
    appMediaUrl: 'https://appmedia.jp/valorant/75609382',
    detailImage: '/valorant/haven.webp',
    cardImage: '/valorant/haven.jpg',
  },
  {
    slug: 'split',
    titleJa: 'スプリット',
    titleEn: 'Split',
    subtitle: 'VALORANT MAP DETAIL',
    overview: '縦方向の攻防が多く、ミッド管理の価値が高いマップです。',
    attackLabel: '攻め',
    defendLabel: '守り',
    focusLabel: '意識したい点',
    attackPoints: ['ミッドを絡めて2方向から圧をかける', 'スモークとフラッシュを重ねて侵入する'],
    defendPoints: ['ミッドの視界を簡単に渡さない', 'ヘブンからのクロスを維持する'],
    focusPoints: ['ミッド支配', 'ヘブンとサイト内の連携'],
    mapPickRate: 52,
    memo: 'ミッドを使えるチームほど攻めの選択肢が増えます。',
    trackerSlug: 'split',
    currentRotation: true,
    appMediaUrl: 'https://appmedia.jp/valorant/75611542',
    detailImage: '/valorant/split.webp',
    cardImage: '/valorant/split.jpg',
  },
  {
    slug: 'bind',
    titleJa: 'バインド',
    titleEn: 'Bind',
    subtitle: 'VALORANT MAP DETAIL',
    overview: 'テレポーターを軸にフェイクと人数寄せが発生しやすいマップです。',
    attackLabel: '攻め',
    defendLabel: '守り',
    focusLabel: '意識したい点',
    attackPoints: ['テレポーターで守りの視線を揺さぶる', '設置前に前線のクリアを丁寧に行う'],
    defendPoints: ['テレポーター音に過剰反応しすぎない', 'ロングの情報を早めに取る'],
    focusPoints: ['フェイクの質', 'ロングとショートの管理'],
    mapPickRate: 47,
    memo: '音情報の扱いが勝敗に直結しやすいマップです。',
    trackerSlug: 'bind',
    currentRotation: true,
    appMediaUrl: 'https://appmedia.jp/valorant/75609295',
    detailImage: '/valorant/bind.webp',
    cardImage: '/valorant/bind.jpg',
  },
  {
    slug: 'breeze',
    titleJa: 'ブリーズ',
    titleEn: 'Breeze',
    subtitle: 'VALORANT MAP DETAIL',
    overview: '広い射線とロング主体の撃ち合いが特徴です。',
    attackLabel: '攻め',
    defendLabel: '守り',
    focusLabel: '意識したい点',
    attackPoints: ['広いサイトを一気に取り切る', 'ロングの圧を継続して守りを下げる'],
    defendPoints: ['不用意にピークしすぎない', '広いサイトをスキルで分断して守る'],
    focusPoints: ['ロングの射線管理', '人数差を作らない守り'],
    mapPickRate: 45,
    memo: 'サイトに入る前の削り合いで優位を取れるかが大切です。',
    trackerSlug: 'breeze',
    currentRotation: true,
    appMediaUrl: 'https://appmedia.jp/valorant/75609289',
    detailImage: '/valorant/breeze.webp',
    cardImage: '/valorant/breeze.jpg',
  },
  {
    slug: 'fracture',
    titleJa: 'フラクチャー',
    titleEn: 'Fracture',
    subtitle: 'VALORANT MAP DETAIL',
    overview: '両側から攻めやすい特殊構造で、守りは連携のズレが出やすいマップです。',
    attackLabel: '攻め',
    defendLabel: '守り',
    focusLabel: '意識したい点',
    attackPoints: ['2方向同時に圧をかける', 'エリア取得後にテンポ良く寄る'],
    defendPoints: ['初動で情報を取り切る', 'どこを捨てるかを早めに決める'],
    focusPoints: ['タイミング合わせ', '守りの分担整理'],
    mapPickRate: 43,
    memo: '連携が崩れると一気にサイトが割られやすいです。',
    trackerSlug: 'fracture',
    currentRotation: true,
    appMediaUrl: 'https://appmedia.jp/valorant/75609286',
    detailImage: '/valorant/fracture.webp',
    cardImage: '/valorant/fracture.jpg',
  },
  {
    slug: 'lotus',
    titleJa: 'ロータス',
    titleEn: 'Lotus',
    subtitle: 'VALORANT MAP DETAIL',
    overview: '3サイトと回転ドアが特徴で、攻守ともに判断量が多いマップです。',
    attackLabel: '攻め',
    defendLabel: '守り',
    focusLabel: '意識したい点',
    attackPoints: ['ドアや破壊可能壁を活用して揺さぶる', 'サイトを見せてからの寄り直しを使う'],
    defendPoints: ['AとCの情報を切らさない', '人数差で無理に取り返さない'],
    focusPoints: ['ドア周りの使い方', '3サイトの人数配分'],
    mapPickRate: 44,
    memo: '情報量が多いので、迷わないコールが大切です。',
    trackerSlug: 'lotus',
    currentRotation: true,
    appMediaUrl: 'https://appmedia.jp/valorant/76382044',
    detailImage: '/valorant/lotus.webp',
    cardImage: '/valorant/lotus.jpg',
  },
  {
    slug: 'pearl',
    titleJa: 'パール',
    titleEn: 'Pearl',
    subtitle: 'VALORANT MAP DETAIL',
    overview: 'ロングとミッドの圧が重要で、攻めの形を丁寧に作る必要があるマップです。',
    attackLabel: '攻め',
    defendLabel: '守り',
    focusLabel: '意識したい点',
    attackPoints: ['ミッドからの圧をかけて守りを分断する', 'ロングの主導権を握って設置を安定させる'],
    defendPoints: ['無理な撃ち合いを減らす', 'サイト内で時間を使って寄りを待つ'],
    focusPoints: ['ロングの人数管理', 'A/B の情報共有'],
    mapPickRate: 41,
    memo: 'ロング主導の撃ち合いが多く、前に出る判断が難しいマップです。',
    trackerSlug: 'pearl',
    currentRotation: true,
    appMediaUrl: 'https://appmedia.jp/valorant/75654946',
    detailImage: '/valorant/pearl.webp',
    cardImage: '/valorant/pearl.jpg',
  },
  {
    slug: 'abyss',
    titleJa: 'アビス',
    titleEn: 'Abyss',
    subtitle: 'VALORANT MAP DETAIL',
    overview: '落下エリアと広いレーンが特徴で、位置取りの精度が問われるマップです。',
    attackLabel: '攻め',
    defendLabel: '守り',
    focusLabel: '意識したい点',
    attackPoints: ['落下リスクを理解してピークする', '広いレーンを使って挟みを作る'],
    defendPoints: ['不用意な前詰めを減らす', '人数不利ではリテイク重視に切り替える'],
    focusPoints: ['落下ラインの把握', '広い射線の共有'],
    mapPickRate: 38,
    memo: '事故が起きやすいので、安定した立ち回りが特に大切です。',
    trackerSlug: 'abyss',
    currentRotation: false,
    appMediaUrl: 'https://appmedia.jp/valorant/78209657',
    detailImage: '/valorant/abyss.webp',
    cardImage: '/valorant/abyss.jpg',
  },
  {
    slug: 'corrode',
    titleJa: 'コロード',
    titleEn: 'Corrode',
    subtitle: 'VALORANT MAP DETAIL',
    overview: 'まだ研究途中の要素が多く、テンポ良い連携と情報共有が差になりやすいマップです。',
    attackLabel: '攻め',
    defendLabel: '守り',
    focusLabel: '意識したい点',
    attackPoints: ['ユーティリティで前線を押し上げる', 'ミッド周辺の強ポジを早めに取る'],
    defendPoints: ['エリアを広げすぎず守る', '寄りやすい形を意識する'],
    focusPoints: ['レーンの距離感', '人数差を作った後の詰め方'],
    mapPickRate: 35,
    memo: '連携が整っているチームほど守りでも攻めでも安定しやすいです。',
    trackerSlug: 'corrode',
    currentRotation: false,
    appMediaUrl: 'https://appmedia.jp/valorant/79061576',
    detailImage: '/valorant/corrode.webp',
    cardImage: '/valorant/corrode.jpg',
  },
]

export function getValorantMap(slug?: string) {
  return VALORANT_MAPS.find((item) => item.slug === slug) ?? null
}
